.TH RISTSENDER "1" "March 2022" "ristsender 0.2.6" "User Commands"
.SH NAME
ristsender \- send a stream via RIST
.SH SYNOPSIS
.B ristsender
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
Reliable Internet Stream Transport (RIST) is a transport protocol
designed for reliable transmission of video over lossy networks
(including the Internet) with low latency and high quality.
.P
ristsender relays an incoming UDP or RTP stream by sending it as a
RIST stream.
.SH OPTIONS
.TP
\fB\-i\fR | \fB\-\-inputurl\fR udp://... or rtp://...
\fBMandatory Option:\fR Comma separated list of input udp or rtp URLs
.TP
\fB\-o\fR | \fB\-\-outputurl\fR rist://...
\fBMandatory Option:\fR Comma separated list of output rist URLs
.TP
\fB\-b\fR | \fB\-\-buffer\fR value
Default buffer size for packet retransmissions
.TP
\fB\-s\fR | \fB\-\-secret\fR PWD
Default pre\-shared encryption secret
.TP
\fB\-e\fR | \fB\-\-encryption\-type\fR TYPE
Default Encryption type (0, 128 = AES\-128, 256 = AES\-256)|
.TP
\fB\-p\fR | \fB\-\-profile\fR number
Rist profile (0 = simple, 1 = main, 2 = advanced)
.TP
\fB\-n\fR | \fB\-\-null\-packet\-deletion\fR
Enable NPD, receiver needs to support this!
.TP
\fB\-S\fR | \fB\-\-statsinterval\fR value (ms)
Interval at which stats get printed, 0 to disable
.TP
\fB\-v\fR | \fB\-\-verbose\-level\fR value
To disable logging: \fB\-1\fR, log levels match syslog levels
.TP
\fB\-r\fR | \fB\-\-remote\-logging\fR IP:PORT
Send logs and stats to this IP:PORT using udp messages
.TP
\fB\-F\fR | \fB\-\-srpfile\fR filepath
When in listening mode, use this file to hold the list
of usernames and passwords to validate against. Use the
\fBristsrppasswd\fR tool to create the line entries.
.TP
\fB\-f\fR | \fB\-\-fast\-start\fR value
Controls data output flow before handshake is completed
 0 = hold data out
 1 = start to send data immediately
.TP
\fB\-h\fR | \fB\-\-help\fR
Show this help
.TP
\fB\-u\fR | \fB\-\-help\-url\fR
Show all the possible url options
.PP
Default values:
.TP
\fB\-\-profile\fR 1
.TP
\fB\-\-statsinterval\fR 1000
.HP
\fB\-\-verbose\-level\fR 6
.SH SEE ALSO
.BR ristreceiver (1),
.BR ristsrppasswd (1),
.BR https://code.videolan.org/rist/librist/-/wikis/LibRIST%20Documentation
.SH AUTHOR
.PP
This manual page was written by Florian Ernst <florian@debian.org>,
for the Debian project (and may be used by others).
